USE STG_Bank;
DELETE FROM STG_TREASURY_PRODUCTS;
DELETE FROM STG_DEPOSIT;
DELETE FROM STG_Credit_Card;
DELETE FROM STG_LOAN;
DELETE FROM STG_PAYMENT;
DELETE FROM STG_TRANSACTIONS;
DELETE FROM STG_TRANSFER;
DELETE FROM STG_WITHDRAWAL;
DELETE FROM STG_Branch;
DELETE FROM STG_Account;
DELETE FROM STG_Transaction_Type;
DELETE FROM STG_Customers;


USE DW_Bank;
DELETE FROM FACT_Treasury_PRODUCT
DELETE FROM DIM_TREASURY_PRODUCTS;
DELETE FROM DIM_DEPOSIT;
DELETE FROM FACT_LOAN;
DELETE FROM DIM_LOAN;
DELETE FROM DIM_PAYMENT;
DELETE FROM DIM_TRANSACTIONS;
DELETE FROM DIM_TRANSFER;
DELETE FROM DIM_WITHDRAWAL;
DELETE FROM Payment_fact
DELETE FROM DIM_Account;
DELETE FROM DIM_Branch;
DELETE FROM DIM_Transaction_Type;
DELETE FROM DIM_Customers;
